from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from src.spice_model import (
    DECODE_THRESHOLD_V,
    _build_constraint_netlist,
    _run_ngspice,
    expected_continuation,
)


@dataclass(frozen=True)
class TransientSample:
    time_seconds: float
    output_voltage: float


@dataclass(frozen=True)
class TransientResponse:
    x0: int
    x3: int
    expected: int
    decoded: int
    final_voltage: float
    target_voltage: float
    signed_margin: float
    rise_time_seconds: float | None
    settling_time_seconds: float | None
    settling_tolerance_voltage: float
    samples: tuple[TransientSample, ...]
    netlist_path: Path
    log_path: Path


def simulate_transient_response(
    x0: int,
    x3: int,
    *,
    supply_voltage: float = 5.0,
    resistance_kohm: float = 10.0,
    capacitance_uf: float = 1.0,
    threshold_voltage: float = DECODE_THRESHOLD_V,
    step_time_ms: float = 0.1,
    end_time_ms: float = 150.0,
    settling_fraction: float = 0.01,
    minimum_settling_tolerance_voltage: float = 0.01,
) -> TransientResponse:
    """
    Simulate the complete RC transient from a zero initial condition.

    The logical circuit is generated by the same constraint compiler used by
    simulate_response(). The transient run uses UIC so that the output
    capacitor begins uncharged.

    Rise time is measured between 10% and 90% of the expected-high target.

    Settling time is the earliest recorded time after which every remaining
    sample stays within the declared tolerance of the target voltage.
    """
    if step_time_ms <= 0:
        raise ValueError("step_time_ms must be greater than zero")

    if end_time_ms <= 0:
        raise ValueError("end_time_ms must be greater than zero")

    if not 0 < settling_fraction < 1:
        raise ValueError("settling_fraction must lie strictly between 0 and 1")

    if minimum_settling_tolerance_voltage <= 0:
        raise ValueError(
            "minimum_settling_tolerance_voltage must be greater than zero"
        )

    netlist_path = Path(f"/tmp/cpc_transient_{x0}_{x3}.cir")
    log_path = Path(f"/tmp/cpc_transient_{x0}_{x3}.out")

    netlist = _build_constraint_netlist(
        x0=x0,
        x3=x3,
        supply_voltage=supply_voltage,
        resistance_kohm=resistance_kohm,
        capacitance_uf=capacitance_uf,
        end_time_ms=end_time_ms,
    )

    original_tran = f".tran 0.1m {end_time_ms}m"
    transient_tran = (
        f".tran {step_time_ms}m {end_time_ms}m uic\n"
        ".print tran v(vout)"
    )

    if original_tran not in netlist:
        raise RuntimeError(
            "Could not locate the transient-analysis directive in the "
            "generated netlist"
        )

    netlist = netlist.replace(
        original_tran,
        transient_tran,
        1,
    )

    netlist_path.write_text(netlist, encoding="utf-8")
    _run_ngspice(netlist_path, log_path)

    samples = _read_transient_samples(log_path)

    if not samples:
        raise RuntimeError(
            f"No transient samples were read from {log_path}"
        )

    expected = expected_continuation(x0, x3)
    target_voltage = supply_voltage if expected == 1 else 0.0
    final_voltage = samples[-1].output_voltage
    decoded = int(final_voltage >= threshold_voltage)

    signed_margin = (
        final_voltage - threshold_voltage
        if expected == 1
        else threshold_voltage - final_voltage
    )

    settling_tolerance_voltage = max(
        abs(target_voltage) * settling_fraction,
        minimum_settling_tolerance_voltage,
    )

    rise_time_seconds = _calculate_rise_time(
        samples=samples,
        target_voltage=target_voltage,
        expected=expected,
    )

    settling_time_seconds = _calculate_settling_time(
        samples=samples,
        target_voltage=target_voltage,
        tolerance_voltage=settling_tolerance_voltage,
    )

    return TransientResponse(
        x0=x0,
        x3=x3,
        expected=expected,
        decoded=decoded,
        final_voltage=final_voltage,
        target_voltage=target_voltage,
        signed_margin=signed_margin,
        rise_time_seconds=rise_time_seconds,
        settling_time_seconds=settling_time_seconds,
        settling_tolerance_voltage=settling_tolerance_voltage,
        samples=samples,
        netlist_path=netlist_path,
        log_path=log_path,
    )


def _read_transient_samples(
    log_path: Path,
) -> tuple[TransientSample, ...]:
    text = log_path.read_text(
        encoding="utf-8",
        errors="replace",
    )

    number = (
        r"[-+]?"
        r"(?:\d+(?:\.\d*)?|\.\d+)"
        r"(?:[eE][-+]?\d+)?"
    )

    row_pattern = re.compile(
        rf"^\s*\d+\s+({number})\s+({number})\s*$",
        flags=re.MULTILINE,
    )

    samples = tuple(
        TransientSample(
            time_seconds=float(match.group(1)),
            output_voltage=float(match.group(2)),
        )
        for match in row_pattern.finditer(text)
    )

    if not samples:
        raise RuntimeError(
            "Could not locate the transient output table in ngspice output.\n"
            f"Log file: {log_path}\n"
            f"Contents:\n{text}"
        )

    return samples


def _calculate_rise_time(
    *,
    samples: tuple[TransientSample, ...],
    target_voltage: float,
    expected: int,
) -> float | None:
    if expected == 0 or target_voltage <= 0:
        return None

    lower_voltage = 0.1 * target_voltage
    upper_voltage = 0.9 * target_voltage

    lower_time = _first_crossing_time(
        samples=samples,
        voltage=lower_voltage,
    )

    upper_time = _first_crossing_time(
        samples=samples,
        voltage=upper_voltage,
    )

    if lower_time is None or upper_time is None:
        return None

    return upper_time - lower_time


def _first_crossing_time(
    *,
    samples: tuple[TransientSample, ...],
    voltage: float,
) -> float | None:
    for sample in samples:
        if sample.output_voltage >= voltage:
            return sample.time_seconds

    return None


def _calculate_settling_time(
    *,
    samples: tuple[TransientSample, ...],
    target_voltage: float,
    tolerance_voltage: float,
) -> float | None:
    last_outside_index: int | None = None

    for index, sample in enumerate(samples):
        error = abs(sample.output_voltage - target_voltage)

        if error > tolerance_voltage:
            last_outside_index = index

    if last_outside_index is None:
        return samples[0].time_seconds

    next_index = last_outside_index + 1

    if next_index >= len(samples):
        return None

    return samples[next_index].time_seconds
